# Generated by Django 3.0 on 2019-12-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20191210_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='perco_marketing_promocional',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(default=0, verbose_name='Preço Promo'),
        ),
    ]
